name: Deploy Backend to Cloud Run

on:
  push:
    branches:
      - master  # Se dispara al subir cambios a la rama principal

env:
  PROJECT_ID: demoapi-mario  # <--- REEMPLAZÁ ESTO CON TU ID REAL
  SERVICE_NAME: demoapi
  REGION: us-central1

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Autenticar en Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Configurar Docker para Artifact Registry
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev --quiet

      - name: Build y Push de la imagen de Docker
        run: |
          # El nombre de la imagen debe coincidir con el repositorio que creamos en Artifact Registry
          IMAGE_NAME=us-central1-docker.pkg.dev/${{ env.PROJECT_ID }}/cloud-run-source-deploy/${{ env.SERVICE_NAME }}:${{ github.sha }}
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME

      - name: Desplegar a Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: ${{ env.SERVICE_NAME }}
          region: ${{ env.REGION }}
          image: us-central1-docker.pkg.dev/${{ env.PROJECT_ID }}/cloud-run-source-deploy/${{ env.SERVICE_NAME }}:${{ github.sha }}
          flags: '--allow-unauthenticated'